# base image
FROM python:3.7-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd && \
    apk add libffi-dev

# set working directory
WORKDIR /usr/src/app 

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt 
RUN pip install -r requirements.txt 

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint-prod.sh
RUN chmod 777 /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app 

# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]